define(['require'], function(require) {

    /**
     * Controller for index generated by Appery.io
     * @module index
     */

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            $scope.visionStatus = {};
        };

        /**
         * user controller variables
         */
        $scope.activeScreen = Apperyio.EntityAPI('ActiveScreen');
    }

    return ['$scope', 'Apperyio', controller];

});