define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Profile generated by Appery.io
     * @module Profile
     */

    APP.controller('Profile', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        };

        /**
         * user controller variables
         */
    }

});